# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

jobs:
  build_and_test:
    executor: my-executor    
    steps:
      - checkout
      - run: pip install tox
      - run: pip install pre-commit
      - run: pre-commit install
      - run: tox
      - run: pre-commit run --all-files

workflows:
  test-python-jobs:
    jobs:
      - build_and_test
