# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  prepare:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: pip install tox
      - run: pip install pre-commit
      - run: pre-commit install
  build:
    steps:
      - run: tox
      - run: pre-commit run --all-files

workflows:
  test-python-jobs:
    jobs:
      - prepare
      - build
